/**
 * PRD Editor Component
 * Rich text editor for creating and managing Product Requirements Documents
 * Saves to workspace for Claude integration
 */

import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import './PRDEditor.css';

const API_URL = 'http://localhost:8080';

interface PRDEditorProps {
  projectName: string;
  projectPath?: string;
  onSave?: (content: string) => void;
}

export function PRDEditor({ projectName, projectPath, onSave }: PRDEditorProps) {
  const [content, setContent] = useState('');
  const [saving, setSaving] = useState(false);
  const [lastSaved, setLastSaved] = useState<Date | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [claudeContext, setClaudeContext] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Default PRD template
  const PRD_TEMPLATE = `# ${projectName} - Product Requirements Document

## Overview
[Describe the project purpose and goals]

## User Stories
As a [type of user], I want to [action] so that [benefit].

## Features
### Feature 1: [Name]
- Description: [What it does]
- Acceptance Criteria:
  - [ ] Criterion 1
  - [ ] Criterion 2
  - [ ] Criterion 3

### Feature 2: [Name]
- Description: [What it does]
- Acceptance Criteria:
  - [ ] Criterion 1
  - [ ] Criterion 2
  - [ ] Criterion 3

## Technical Requirements
### Architecture
- Frontend: [React, Vue, etc.]
- Backend: [Python, Node.js, etc.]
- Database: [PostgreSQL, MongoDB, etc.]
- Infrastructure: [AWS, Docker, etc.]

### APIs
- Endpoint 1: [Description]
- Endpoint 2: [Description]

### Data Models
- Model 1: [Description]
- Model 2: [Description]

## Success Criteria
- [ ] All features implemented and tested
- [ ] Performance meets requirements
- [ ] Security requirements met
- [ ] Documentation complete
- [ ] Deployed to production

## Timeline
- Phase 1: [Description] - [Duration]
- Phase 2: [Description] - [Duration]
- Phase 3: [Description] - [Duration]

## Dependencies
- [List any external dependencies or integrations]

## Risks and Mitigation
- Risk 1: [Description] → Mitigation: [Strategy]
- Risk 2: [Description] → Mitigation: [Strategy]

---
Generated by BuildRunner UI - ${new Date().toISOString()}
`;

  useEffect(() => {
    // Load existing PRD or use template
    loadPRD();
  }, [projectName, projectPath]);

  const loadPRD = async () => {
    // If we have a project path, load from actual project file
    if (projectPath) {
      try {
        const response = await axios.post(`${API_URL}/api/prd/read`, {
          project_path: projectPath
        });

        if (response.data.success && response.data.content) {
          setContent(response.data.content);
          setError(null);
        } else {
          // No PRD found, use template
          setContent(PRD_TEMPLATE);
        }
      } catch (err: any) {
        console.error('Failed to load PRD:', err);
        setContent(PRD_TEMPLATE);
      }
    } else {
      // Fallback to old workspace method if no project path
      try {
        const response = await axios.get(
          `${API_URL}/api/workspace/output/read/${projectName}_prd.md`
        );
        if (response.data.content) {
          setContent(response.data.content);
        } else {
          setContent(PRD_TEMPLATE);
        }
      } catch (err) {
        setContent(PRD_TEMPLATE);
      }
    }
  };

  const savePRD = async () => {
    setSaving(true);
    setError(null);

    try {
      const response = await axios.post(`${API_URL}/api/workspace/prd/save`, {
        project_name: projectName,
        content: content,
        metadata: {
          updated_at: new Date().toISOString(),
          editor: 'BuildRunner UI'
        }
      });

      if (response.data.success) {
        setLastSaved(new Date());
        if (onSave) {
          onSave(content);
        }

        // Show trigger file path
        setClaudeContext(response.data.trigger);
      }
    } catch (err: any) {
      setError(err.response?.data?.detail || err.message);
    } finally {
      setSaving(false);
    }
  };

  const generateClaudeContext = async () => {
    try {
      const response = await axios.post(
        `${API_URL}/api/workspace/context/generate/${projectName}`
      );

      if (response.data.success) {
        setClaudeContext(response.data.context_file);

        // Copy command to clipboard
        const command = `claude ${response.data.context_file}`;
        navigator.clipboard.writeText(command).then(() => {
          setError(null);
          alert(`Command copied to clipboard:\n${command}`);
        });
      }
    } catch (err: any) {
      setError(err.response?.data?.detail || err.message);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    // Save on Cmd/Ctrl+S
    if ((e.metaKey || e.ctrlKey) && e.key === 's') {
      e.preventDefault();
      savePRD();
    }

    // Tab support in textarea
    if (e.key === 'Tab') {
      e.preventDefault();
      const start = textareaRef.current?.selectionStart || 0;
      const end = textareaRef.current?.selectionEnd || 0;
      const newContent =
        content.substring(0, start) + '  ' + content.substring(end);
      setContent(newContent);

      // Restore cursor position
      setTimeout(() => {
        if (textareaRef.current) {
          textareaRef.current.selectionStart = start + 2;
          textareaRef.current.selectionEnd = start + 2;
        }
      }, 0);
    }
  };

  return (
    <div className="prd-editor">
      <div className="editor-header">
        <h2>📝 PRD Editor - {projectName}</h2>
        <div className="editor-actions">
          <button
            onClick={savePRD}
            disabled={saving}
            className="save-btn"
          >
            {saving ? 'Saving...' : '💾 Save PRD'}
          </button>
          <button
            onClick={generateClaudeContext}
            className="context-btn"
          >
            🤖 Generate Claude Context
          </button>
          {lastSaved && (
            <span className="last-saved">
              Last saved: {lastSaved.toLocaleTimeString()}
            </span>
          )}
        </div>
      </div>

      <div className="editor-body">
        <textarea
          ref={textareaRef}
          className="prd-textarea"
          value={content}
          onChange={(e) => setContent(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Start writing your PRD..."
          spellCheck={true}
        />

        <div className="editor-sidebar">
          <div className="markdown-tips">
            <h4>📚 Markdown Tips</h4>
            <ul>
              <li># Heading 1</li>
              <li>## Heading 2</li>
              <li>**bold text**</li>
              <li>*italic text*</li>
              <li>- List item</li>
              <li>[ ] Checkbox</li>
              <li>`code`</li>
              <li>```code block```</li>
            </ul>
          </div>

          {claudeContext && (
            <div className="claude-ready">
              <h4>✅ Claude Ready</h4>
              <p>Context file created:</p>
              <code>{claudeContext}</code>
              <p>Run in terminal:</p>
              <code>claude {claudeContext}</code>
            </div>
          )}

          {error && (
            <div className="error-message">
              ❌ {error}
            </div>
          )}

          <div className="workspace-info">
            <h4>📁 Workspace</h4>
            <p>PRD saved to:</p>
            <code>/workspace/prd/{projectName}.md</code>
            <p>Claude reads from:</p>
            <code>/workspace/output/</code>
          </div>
        </div>
      </div>

      <div className="editor-footer">
        <span className="char-count">
          {content.length} characters | {content.split('\n').length} lines
        </span>
        <span className="shortcuts">
          Cmd/Ctrl+S to save | Tab for indent
        </span>
      </div>
    </div>
  );
}