"""
Design Config Generator - Generate framework-specific design configs from industry profiles
"""

import json
from typing import Dict


class DesignGenerator:
    """Generate framework-specific design configs from industry profiles"""

    def __init__(self, framework: str = 'tailwind'):
        """
        Initialize generator

        Args:
            framework: Target framework ('tailwind', 'mui', 'chakra')
        """
        self.framework = framework.lower()

        if self.framework not in ['tailwind', 'mui', 'chakra']:
            raise ValueError(f"Unsupported framework: {framework}. Supported: tailwind, mui, chakra")

    def generate_config(self, profile: Dict) -> str:
        """
        Generate config file based on framework

        Args:
            profile: Industry profile dictionary

        Returns:
            Config file content as string
        """
        if self.framework == 'tailwind':
            return self._generate_tailwind(profile)
        elif self.framework == 'mui':
            return self._generate_mui(profile)
        elif self.framework == 'chakra':
            return self._generate_chakra(profile)
        else:
            raise ValueError(f"Unsupported framework: {self.framework}")

    def _generate_tailwind(self, profile: Dict) -> str:
        """Generate Tailwind CSS config from industry profile"""
        colors = profile.get('color_scheme', {})
        typography = profile.get('typography', {})
        industry = profile.get('industry', 'Unknown')
        naics = profile.get('naics_code', 'N/A')

        # Extract color palette
        primary_color = colors.get('primary', '#3B82F6')
        secondary_color = colors.get('secondary', '#10B981')
        accent_color = colors.get('accent', '#F59E0B')

        # Build color palette
        color_palette = {
            'primary': primary_color,
            'secondary': secondary_color,
            'accent': accent_color,
        }

        # Add additional colors if available
        if 'palette' in colors:
            color_palette.update(colors['palette'])

        # Extract typography settings
        font_family = typography.get('fonts', {})
        if isinstance(font_family, dict):
            heading_font = font_family.get('heading', 'Inter')
            body_font = font_family.get('body', 'Inter')
        else:
            heading_font = body_font = 'Inter'

        font_sizes = typography.get('scales', {
            'xs': '0.75rem',
            'sm': '0.875rem',
            'base': '1rem',
            'lg': '1.125rem',
            'xl': '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
        })

        return f"""/** @type {{import('tailwindcss').Config}} */
module.exports = {{
  content: [
    './src/**/*.{{js,jsx,ts,tsx}}',
    './public/index.html',
  ],
  theme: {{
    extend: {{
      colors: {json.dumps(color_palette, indent=8)},
      fontFamily: {{
        heading: ['{heading_font}', 'sans-serif'],
        body: ['{body_font}', 'sans-serif'],
      }},
      fontSize: {json.dumps(font_sizes, indent=8)},
    }},
  }},
  plugins: [],
}}

// Generated by BuildRunner 3.0 Design System
// Industry: {industry}
// NAICS Code: {naics}
// Generated from Synapse industry profile database
"""

    def _generate_mui(self, profile: Dict) -> str:
        """Generate Material-UI theme from industry profile"""
        colors = profile.get('color_scheme', {})
        typography = profile.get('typography', {})
        industry = profile.get('industry', 'Unknown')

        primary_color = colors.get('primary', '#3B82F6')
        secondary_color = colors.get('secondary', '#10B981')

        # Extract font settings
        font_family = typography.get('fonts', {})
        if isinstance(font_family, dict):
            heading_font = font_family.get('heading', 'Roboto')
            body_font = font_family.get('body', 'Roboto')
        else:
            heading_font = body_font = 'Roboto'

        return f"""// Material-UI Theme Configuration
// Generated by BuildRunner 3.0 Design System
// Industry: {industry}

import {{ createTheme }} from '@mui/material/styles';

export const theme = createTheme({{
  palette: {{
    primary: {{
      main: '{primary_color}',
    }},
    secondary: {{
      main: '{secondary_color}',
    }},
  }},
  typography: {{
    fontFamily: '{body_font}, sans-serif',
    h1: {{
      fontFamily: '{heading_font}, sans-serif',
    }},
    h2: {{
      fontFamily: '{heading_font}, sans-serif',
    }},
    h3: {{
      fontFamily: '{heading_font}, sans-serif',
    }},
  }},
}});

export default theme;
"""

    def _generate_chakra(self, profile: Dict) -> str:
        """Generate Chakra UI theme from industry profile"""
        colors = profile.get('color_scheme', {})
        typography = profile.get('typography', {})
        industry = profile.get('industry', 'Unknown')

        primary_color = colors.get('primary', '#3B82F6')
        secondary_color = colors.get('secondary', '#10B981')

        # Extract font settings
        font_family = typography.get('fonts', {})
        if isinstance(font_family, dict):
            heading_font = font_family.get('heading', 'Inter')
            body_font = font_family.get('body', 'Inter')
        else:
            heading_font = body_font = 'Inter'

        return f"""// Chakra UI Theme Configuration
// Generated by BuildRunner 3.0 Design System
// Industry: {industry}

import {{ extendTheme }} from '@chakra-ui/react';

export const theme = extendTheme({{
  colors: {{
    primary: {{
      500: '{primary_color}',
    }},
    secondary: {{
      500: '{secondary_color}',
    }},
  }},
  fonts: {{
    heading: `'{heading_font}', sans-serif`,
    body: `'{body_font}', sans-serif`,
  }},
}});

export default theme;
"""


def main():
    """Test design generator"""
    # Sample profile
    profile = {
        'industry': 'Healthcare',
        'naics_code': '621111',
        'color_scheme': {
            'primary': '#0EA5E9',
            'secondary': '#10B981',
            'accent': '#F59E0B',
        },
        'typography': {
            'fonts': {
                'heading': 'Poppins',
                'body': 'Inter',
            },
            'scales': {
                'xs': '0.75rem',
                'sm': '0.875rem',
                'base': '1rem',
                'lg': '1.125rem',
                'xl': '1.25rem',
            }
        }
    }

    print("=" * 70)
    print("Design Config Generator Test")
    print("=" * 70)
    print()

    # Generate Tailwind config
    print("Generating Tailwind config...")
    generator = DesignGenerator('tailwind')
    tailwind_config = generator.generate_config(profile)
    print(tailwind_config)
    print()

    print("=" * 70)
    print("✅ Test completed!")
    print("=" * 70)


if __name__ == "__main__":
    main()
